name: Deploy Hexo Blog

on:
  push:
    branches:
      - main  # 当 main 分支有新提交时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g hexo-cli
          npm install

      - name: Generate static files
        run: hexo generate

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create and switch to `public` branch
        run: |
          git checkout -b public || git checkout public

      - name: Update `public` branch
        run: |
          git rm -r --ignore-unmatch *
          cp -r public/* .
          git add .
          git commit -m "Update public branch with new static files" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: public
          github_token: ${{ secrets.GITHUB_TOKEN }}
